const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('trim', {
  searchApps:    ()           => ipcRenderer.invoke('trim:search-apps'),
  getIcon:       (exePath)    => ipcRenderer.invoke('trim:get-icon', exePath),
  getUsage:      ()           => ipcRenderer.invoke('trim:get-usage'),
  getDisplayScale: ()         => ipcRenderer.invoke('trim:get-display-scale'),
  openApp:       (appPath, appName) => ipcRenderer.invoke('trim:open-app', appPath, appName),
  aiQuery:       (query, usePro, forceShow, followUp, pastedImages) => ipcRenderer.invoke('trim:ai-query', query, usePro, forceShow, followUp, pastedImages),
  searchFolders: (query)      => ipcRenderer.invoke('trim:search-folders', query),
  onFolderSearchUpdate: (cb)  => ipcRenderer.on('trim:folder-search-update', (_e, data) => cb(data)),
  offFolderSearchUpdate: ()   => ipcRenderer.removeAllListeners('trim:folder-search-update'),
  openFolder:    (folderPath) => ipcRenderer.invoke('trim:open-folder', folderPath),
  loadSettings:  ()           => ipcRenderer.invoke('trim:load-settings'),
  saveSettings:  (data)       => ipcRenderer.invoke('trim:save-settings', data),
  hideWindow:    ()           => ipcRenderer.send('trim:hide-window'),
  resizeWindow:  (h)          => ipcRenderer.invoke('trim:resize-window', h),
  onWindowShown: (cb)         => ipcRenderer.on('trim:window-shown', cb),
  onWindowHidden:(cb)         => ipcRenderer.on('trim:window-hidden', cb),
  onAIStatus:    (cb)         => ipcRenderer.on('trim:ai-status', (_e, data) => cb(data)),
  offAIStatus:   ()           => ipcRenderer.removeAllListeners('trim:ai-status'),
  cleanup:       ()           => ipcRenderer.invoke('trim:cleanup'),
  clearCache:    ()           => ipcRenderer.invoke('trim:clear-cache'),
  getCacheSize:  ()           => ipcRenderer.invoke('trim:get-cache-size'),
  onConfirmAction: (cb)       => ipcRenderer.on('trim:confirm-action', (_e, details) => cb(details)),
  respondConfirmAction: (approved) => ipcRenderer.send('trim:confirm-action-response', approved),
  setBackgroundMaterial: (type, appColor) => ipcRenderer.invoke('trim:set-background-material', type, appColor),
  updateShortcut: (accelerator) => ipcRenderer.invoke('trim:update-shortcut', accelerator),
  suspendShortcut: () => ipcRenderer.invoke('trim:suspend-shortcut'),
  resumeShortcut: () => ipcRenderer.invoke('trim:resume-shortcut'),
  onSystemKey: (cb) => ipcRenderer.on('trim:system-key', (_e, accel) => cb(accel)),
  offSystemKey: () => ipcRenderer.removeAllListeners('trim:system-key'),
  onUpdateReady: (cb) => ipcRenderer.on('trim:update-ready', cb),
  quitAndInstall: () => ipcRenderer.send('trim:quit-and-install'),
  copyImageToClipboard: (dataUri) => ipcRenderer.invoke('trim:copy-image', dataUri),
  readClipboardImage: () => ipcRenderer.invoke('trim:read-clipboard-image'),
  isDevMode: () => ipcRenderer.invoke('trim:is-dev-mode'),
  revertToTurn: (turnIndex) => ipcRenderer.invoke('trim:revert-to-turn', turnIndex),
  doTask: (task) => ipcRenderer.invoke('trim:do-task', task),
  doFollowUp: (text) => ipcRenderer.invoke('trim:do-follow-up', text),
  doCloseBrowser: () => ipcRenderer.send('trim:do-close-browser'),
  doAbort: () => ipcRenderer.send('trim:do-abort'),
  onDoStatus: (cb) => ipcRenderer.on('trim:do-status', (_e, data) => cb(data)),
  offDoStatus: () => ipcRenderer.removeAllListeners('trim:do-status'),
  onDoAbortHotkey: (cb) => ipcRenderer.on('trim:do-abort-hotkey', cb),
  offDoAbortHotkey: () => ipcRenderer.removeAllListeners('trim:do-abort-hotkey'),
  suppressBlur: (flag) => ipcRenderer.send('trim:suppress-blur', flag),
});
