const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('trim', {
  searchApps:    ()           => ipcRenderer.invoke('trim:search-apps'),
  getIcon:       (exePath)    => ipcRenderer.invoke('trim:get-icon', exePath),
  getUsage:      ()           => ipcRenderer.invoke('trim:get-usage'),
  getDisplayScale: ()         => ipcRenderer.invoke('trim:get-display-scale'),
  openApp:       (appPath, appName) => ipcRenderer.invoke('trim:open-app', appPath, appName),
  aiQuery:       (query, usePro, forceShow, followUp) => ipcRenderer.invoke('trim:ai-query', query, usePro, forceShow, followUp),
  searchFolders: (query)      => ipcRenderer.invoke('trim:search-folders', query),
  onFolderSearchUpdate: (cb)  => ipcRenderer.on('trim:folder-search-update', (_e, data) => cb(data)),
  offFolderSearchUpdate: ()   => ipcRenderer.removeAllListeners('trim:folder-search-update'),
  openFolder:    (folderPath) => ipcRenderer.invoke('trim:open-folder', folderPath),
  loadSettings:  ()           => ipcRenderer.invoke('trim:load-settings'),
  saveSettings:  (data)       => ipcRenderer.invoke('trim:save-settings', data),
  hideWindow:    ()           => ipcRenderer.send('trim:hide-window'),
  resizeWindow:  (h)          => ipcRenderer.invoke('trim:resize-window', h),
  onWindowShown: (cb)         => ipcRenderer.on('trim:window-shown', cb),
  onWindowHidden:(cb)         => ipcRenderer.on('trim:window-hidden', cb),
  onAIStatus:    (cb)         => ipcRenderer.on('trim:ai-status', (_e, data) => cb(data)),
  offAIStatus:   ()           => ipcRenderer.removeAllListeners('trim:ai-status'),
  cleanup:       ()           => ipcRenderer.invoke('trim:cleanup'),
  clearCache:    ()           => ipcRenderer.invoke('trim:clear-cache'),
  getCacheSize:  ()           => ipcRenderer.invoke('trim:get-cache-size'),
  onConfirmAction: (cb)       => ipcRenderer.on('trim:confirm-action', (_e, details) => cb(details)),
  respondConfirmAction: (approved) => ipcRenderer.send('trim:confirm-action-response', approved),
});
